const produtos = [
  { id: 1, nome: "Coca-Cola Lata 350ml", imagem: "imagens/Coca-Cola.webp", quantidade: 50, categoria: "Bebidas Não Alcoólicas", valor: 4.50 },
  { id: 2, nome: "Guaraná Antártica 2L", imagem: "imagens/guarana-antartica.webp", quantidade: 10, categoria: "Bebidas Não Alcoólicas", valor: 7.00 },
  { id: 3, nome: "Água Mineral com Gás 500ml", imagem: "imagens/agua-mineral-com-gas.png", quantidade: 100, categoria: "Bebidas Não Alcoólicas", valor: 2.50 },
  { id: 4, nome: "Água Mineral sem Gás 500ml", imagem: "imagens/agua-mineral-sem-gas.webp", quantidade: 80, categoria: "Bebidas Não Alcoólicas", valor: 2.30 },
  { id: 5, nome: "Cerveja Heineken 350ml", imagem: "imagens/cerveja-heineken.jpeg", quantidade: 40, categoria: "Bebidas Alcoólicas", valor: 6.50 },
  { id: 6, nome: "Cerveja Skol 350ml", imagem: "imagens/cerveja-skol.jpeg", quantidade: 60, categoria: "Bebidas Alcoólicas", valor: 5.00 },
  { id: 7, nome: "Suco de Laranja Natural 1L", imagem: "imagens/suco-laranja-natural-one.webp", quantidade: 25, categoria: "Bebidas Não Alcoólicas", valor: 8.00 },
  { id: 8, nome: "Arroz Tipo 1 5kg", imagem: "imagens/arroz-tipo1.webp", quantidade: 35, categoria: "Mercearia", valor: 18.00 },
  { id: 9, nome: "Feijão Carioca 1kg", imagem: "imagens/feijao-carioca.webp", quantidade: 50, categoria: "Mercearia", valor: 7.50 },
  { id: 10, nome: "Açúcar Cristal 1kg", imagem: "imagens/acucar-cristal.webp", quantidade: 40, categoria: "Mercearia", valor: 4.20 },
  { id: 11, nome: "Macarrão Espaguete 500g", imagem: "imagens/macarrao-espaguete.webp", quantidade: 45, categoria: "Mercearia", valor: 3.50 },
  { id: 12, nome: "Molho de Tomate 340g", imagem: "imagens/molho-tomate.webp", quantidade: 60, categoria: "Mercearia", valor: 2.80 },
  { id: 13, nome: "Pão de Forma 500g", imagem: "imagens/pao-de-forma.webp", quantidade: 30, categoria: "Padaria", valor: 6.00 },
  { id: 14, nome: "Queijo Mussarela Fatiado 150g", imagem: "imagens/queijo-mussarela-fatiado.webp", quantidade: 20, categoria: "Laticínios", valor: 10.00 },
  { id: 15, nome: "Café em Pó 500g", imagem: "imagens/cafe-em-po.jpeg", quantidade: 40, categoria: "Mercearia", valor: 12.00 },
  { id: 16, nome: "Barra de Chocolate Lacta 90g", imagem: "imagens/barra-chocolate-lacta.png", quantidade: 70, categoria: "Confeitaria", valor: 4.00 },
  { id: 17, nome: "Chocolate Bis 126g", imagem: "imagens/chocolate-bis.jpeg", quantidade: 65, categoria: "Confeitaria", valor: 5.50 },
  { id: 18, nome: "Bolo de Chocolate 500g", imagem: "imagens/bolo-chocolate.webp", quantidade: 15, categoria: "Confeitaria", valor: 20.00 },
  { id: 19, nome: "Doritos 150g", imagem: "imagens/doritos.webp", quantidade: 50, categoria: "Salgadinhos", valor: 6.00 },
  { id: 20, nome: "Ruffles 150g", imagem: "imagens/ruffles.webp", quantidade: 45, categoria: "Salgadinhos", valor: 6.00 },
  { id: 21, nome: "Cheetos 120g", imagem: "imagens/cheetos.jpeg", quantidade: 40, categoria: "Salgadinhos", valor: 5.00 },
  { id: 22, nome: "Halls Extra Forte 30g", imagem: "imagens/halls-extra-forte.webp", quantidade: 100, categoria: "Balas e Pastilhas", valor: 2.00 },
  { id: 23, nome: "Sabonete Lux 85g", imagem: "imagens/sabonete-lux.webp", quantidade: 80, categoria: "Higiene Pessoal", valor: 3.50 },
  { id: 24, nome: "Sabonete em Pó Omo 500g", imagem: "imagens/sabonete-em-po-omo.jpeg", quantidade: 25, categoria: "Limpeza", valor: 15.00 },
  { id: 25, nome: "Shampoo Seda 300ml", imagem: "imagens/shampoo-seda.jpeg", quantidade: 30, categoria: "Higiene Pessoal", valor: 12.00 },
  { id: 26, nome: "Desinfetante Ypê 500ml", imagem: "imagens/desinfetante-ype.webp", quantidade: 40, categoria: "Limpeza", valor: 7.00 },
  { id: 27, nome: "Detergente Líquido 500ml", imagem: "imagens/detergente.webp", quantidade: 50, categoria: "Limpeza", valor: 4.00 },
  { id: 28, nome: "Café em Pó 500g", imagem: "imagens/cafe-em-po.jpeg", quantidade: 40, categoria: "Mercearia", valor: 12.00 },
  { id: 29, nome: "Vinho Tinto Suave 750ml", imagem: "imagens/vinho-tinto-suave.jpeg", quantidade: 20, categoria: "Bebidas Alcoólicas", valor: 25.00 },
  { id: 30, nome: "Pasta de Dente 90g", imagem: "imagens/pasta-de-dente.webp", quantidade: 50, categoria: "Higiene Pessoal", valor: 6.50 }
];
